---
- hosts: webservers
  become: true
  tasks:
    - name: "Install epel repository"
      yum:
        name: epel-release
    - name: "Install nginx"
      yum:
        name: nginx
        state: present
    - name: "Start nginx"
      service:
        name: nginx
        state: started
        enabled: yes
    - name: "Task 1"
      shell: "echo $HOSTNAME"
      register: print_hostname
    - debug: msg="{{ print_hostname.stdout }}"

    - name: "Task 2"
      shell: date
      register: print_date 
    - debug: msg="{{ print_date.stdout }}"

    - name: "Task 2"
      shell: whoami
      register: response_whoami
    - debug: msg="{{ response_whoami.stdout }}"

    - name: "Task 3"
      shell: uname -a
      register: response_uname
    - debug: msg="{{ response_uname.stdout }}"

    - name: "Task 4 - Get free ram percentage"
      shell: free | grep Mem | awk '{print $4/$2 * 100.0}'
      register: response_free
    - debug: msg="{{ response_free.stdout }}"

    - name: "Task 5"
      shell: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
      register: response_cpuinfo
    - debug: msg="{{ response_cpuinfo.stdout }}"

    - name: "Configure nginx"
      template:
        src: templates/index.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: wheel
        mode: "0644"
